### ISSUE TITLE
Remove the mysqldb connection in dev branch 

### ISSUE THREAD

**Issue by memetics19** [MeenalV/Django-BlogSite#2]
Please remove mysqldb connection in dev branch @Saurabh-Sn . We will integrate with postgresql and host it on heroku

**Comment by memetics19** [comment]
@Saurabh-Sn  where is the blog_category table?


![image](https://user-images.githubusercontent.com/50732218/79874801-6a851c00-8406-11ea-9683-a3a2c7deecb9.png)

**Comment by MeenalV** [comment]
Its in the blog app, you can check there

**Comment by memetics19** [comment]
okay, thanks i'll check it

**Comment by memetics19** [comment]
i think issue as been solved by @MeenalV  closing this issue
